---
trigger:
  branches:
    include:
    - dev
  paths:
    exclude: 
    - '**/*.yaml'

variables:
- name: azureServiceConnection
  value: 'wif-ado-dev-depositorgination'
- name: dev-depositorigination-frontend
  value: 'devalbauksst001'

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    displayName: Build - Deposit Origination frontend - DEV
    jobs:
      - job: 
        displayName: 'Build - Deposit Origination frontend - DEV'
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: 19.x
            displayName: Install Node.js

          - script: |
              rm -rf node_modules && npm cache clean --force
              npm install
              npm run build
            displayName: npm install and build

          - task: CopyFiles@2
            displayName: Copy files to staging
            inputs:
              SourceFolder: build/
              TargetFolder: $(Build.ArtifactStagingDirectory)

          - task: PublishBuildArtifacts@1
            displayName: "Publish Artifact: drop"
            inputs:
              PathtoPublish: $(Build.ArtifactStagingDirectory)

  - stage: DeployDepositOriginationFrontenddev
    displayName: Deploy Deposit Origination Frontend - DEV
    jobs:
    - deployment: DepositOriginationDeploy
      displayName: Deploy Deposit Origination Frontend - DEV
      environment: 'dev-depositorigination-frontend'
      strategy: 
        runOnce:
            deploy:
              steps:
              - task: AzureCLI@2
                displayName: Deploy Frontend - dev
                inputs:
                  azureSubscription: $(azureServiceConnection)
                  scriptType: 'pscore'
                  scriptLocation: 'inlineScript'
                  inlineScript: |
                    az storage blob upload-batch -d '$web' --account-name $(dev-depositorigination-frontend) -s $(Pipeline.Workspace)/drop --overwrite --auth-mode login
