---
trigger:
  branches:
    include:
    - main
  paths:
    exclude: 
    - '**/*.yaml'

variables:
- name: azureServiceConnection
  value: 'spn-ado-prd-depositorigination'
- name: prd-depositorigination-frontend
  value: 'prdalbauksst001'
- name: prd-depositorigination-frontend-DR
  value: 'prdalbaeurst001'

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    jobs:
      - job: 
        displayName: 'Build - Deposit Origination frontend - Production'
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: 19.x
            displayName: Install Node.js

          - script: |
              rm -rf node_modules && npm cache clean --force
              npm install
              npm run build:prd
            displayName: npm install and build

          - task: CopyFiles@2
            displayName: Copy files to staging
            inputs:
              SourceFolder: build/
              TargetFolder: $(Build.ArtifactStagingDirectory)

          - task: PublishBuildArtifacts@1
            displayName: "Publish Artifact: drop"
            inputs:
              PathtoPublish: $(Build.ArtifactStagingDirectory)

  - stage: DeployDepositsOriginationFrontendPpd
    displayName: Deploy Deposit Origination Frontend - Production
    jobs:
    - deployment: DepositOriginationDeploy
      displayName: Deploy Deposit Origination Frontend - Production
      environment: 'prd-depositorigination-frontend'
      strategy: 
        runOnce:
            deploy:
              steps:
              - task: AzureCLI@2
                displayName: Deploy Frontend - Production
                inputs:
                  azureSubscription: $(azureServiceConnection)
                  scriptType: 'pscore'
                  scriptLocation: 'inlineScript'
                  inlineScript: |
                    az storage blob upload-batch -d '$web' --account-name $(prd-depositorigination-frontend) -s $(Pipeline.Workspace)/drop --overwrite --auth-mode login
              - task: AzureCLI@2
                displayName: Deploy Frontend - Production DR
                inputs:
                  azureSubscription: $(azureServiceConnection)
                  scriptType: 'pscore'
                  scriptLocation: 'inlineScript'
                  inlineScript: |
                    az storage blob upload-batch -d '$web' --account-name $(prd-depositorigination-frontend-DR) -s $(Pipeline.Workspace)/drop --overwrite --auth-mode login
