# Node.js Express Web App to Linux on Azure
# Build a Node.js Express app and deploy it to Azure as a Linux web app.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - uat

variables:
  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: 'bdbb8038-9532-40ae-921b-18c169f82e31'

  # Web app name
  webAppName: 'uat-alba-uks-webapp-001'

  # Environment name
  environmentName: 'uat-alba-uks-webapp-001'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
  - stage: Build
    displayName: Build stage
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: $(vmImageName)

        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '20.9.0'
            displayName: 'Install Node.js'

          - task: UseNode@1
            inputs:
              versionSpec: '20.9.0'
            displayName: 'Use Node.js'

          - task: ArchiveFiles@2
            displayName: 'Archive files'
            inputs:
              rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
              includeRootFolder: false
              archiveType: zip
              archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
              replaceExistingArchive: true

          - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
            artifact: drop

  - stage: Deploy
    displayName: Deploy stage
    dependsOn: Build
    condition: succeeded()
    jobs:
      - deployment: Deploy
        displayName: Deploy
        environment: $(environmentName)
        pool:
          vmImage: $(vmImageName)
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureRmWebAppDeployment@4
                  displayName: 'Azure Web App Deploy: uat-alba-uks-webapp-001'
                  inputs:
                    ConnectionType: 'AzureRM'
                    azureSubscription: $(azureSubscription)
                    appType: webAppLinux
                    WebAppName: $(webAppName)
                    packageForLinux: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'
                    deployToSlotOrASE: true
                    ResourceGroupName: 'uat-alba-uks-rg-ops'
                    RuntimeStack: 'NODE|20-lts'
                    StartupCommand: 'npm run start'
                    ScriptType: 'Inline Script'
                    enableCustomDeployment: true
                    DeploymentType: 'webDeploy'
                    TakeAppOfflineFlag: true
                    InlineScript: |
                      rm -rf .next
                      npm install
                      npm run build:uat --if-present
